name: SurfUnstuck
version: "2.2"
main: dev.slne.unstuck.bukkit.BukkitMain
api-version: "1.20"

dependencies:
    server:
        WorldGuard:
            load: BEFORE
            required: true
            join-classpath: true
        CommandAPI:
            load: BEFORE
            required: true
            join-classpath: true
