name: SurfUnstuck
version: "2.2"
main: dev.slne.unstuck.bukkit.BukkitMain
api-version: "1.20"

loader: dev.slne.unstuck.bukkit.BukkitLoader

dependencies:
    server:
        WorldGuard:
            load: BEFORE
            required: false
            join-classpath: true
