name: SurfUnstuck
version: "1.0"
main: dev.slne.unstuck.bukkit.BukkitMain
api-version: "1.19"

bootstrapper: dev.slne.unstuck.bukkit.BukkitBootstapper
loader: dev.slne.unstuck.bukkit.BukkitLoader

dependencies:
    - name: WorldGuard
      required: true
      bootstrap: false
    - name: ProtocolLib
      required: false
      bootstrap: false
    - name: ProtocolSupport
      required: false
      bootstrap: false
    - name: ViaVersion
      required: false
      bootstrap: false
    - name: ViaBackwards
      required: false
      bootstrap: false
    - name: ViaRewind
      required: false
      bootstrap: false
    - name: Geyser-Spigot
      required: false
      bootstrap: false

permissions:
    unstuck.use:
        default: true
        description: Allows you to use /unstuck
    unstuck.notify:
        default: op
        description: Allows you to see unstuck alerts
    unstuck.teleport:
        default: op
        description: Allows you to use /unstucktp
