name: SurfUnstuck
version: "2.0"
main: dev.slne.unstuck.bukkit.BukkitMain
api-version: "1.19"

bootstrapper: dev.slne.unstuck.bukkit.BukkitBootstrapper
loader: dev.slne.unstuck.bukkit.BukkitLoader

dependencies:
    - name: WorldGuard
      required: true
      bootstrap: false
