name: SurfUnstuck
version: "2.1"
main: dev.slne.unstuck.bukkit.BukkitMain
api-version: "1.19"

loader: dev.slne.unstuck.bukkit.BukkitLoader

dependencies:
    - name: WorldGuard
      required: true
      bootstrap: false
