name: SurfAntiExploit
version: "1.0"
main: dev.slne.antiexploit.bukkit.BukkitMain
api-version: "1.19"

bootstrapper: dev.slne.antiexploit.bukkit.BukkitBootstrapper
loader: dev.slne.antiexploit.bukkit.BukkitLoader
