name: SurfUnstuck
version: 1.0
api: "1.19"
api-version: "1.19"
authors:
    - SLNE Dev Team

depend:
    - WorldGuard

main: dev.slne.unstuck.bukkit.BukkitMain

commands:
    stuck:
        aliases: unstuck
        usage: /unstuck
        description: Allows the player to teleport back to spawn if they are stuck.
        permission: unstuck.use
    unstucktp:
        usage: /unstucktp
        description: Allows the player to teleport to a location
        permission: unstuck.teleport

permissions:
    unstuck.use:
        default: true
        description: Allows you to use /unstuck
    unstuck.notify:
        default: op
        description: Allows you to see unstuck alerts
    unstuck.teleport:
        default: op
        description: Allows you to use /unstucktp
